/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opRegistrarEquipo = new javax.swing.JMenuItem();
        opRegistrarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opRegistrarVenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opListarReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("escritorio"); // NOI18N

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        jMenu1.setText("Registro");

        opRegistrarEquipo.setText("Registrar equipo");
        opRegistrarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRegistrarEquipoActionPerformed(evt);
            }
        });
        jMenu1.add(opRegistrarEquipo);

        opRegistrarCliente.setText("Registrar cliente");
        opRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRegistrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(opRegistrarCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");

        opRegistrarVenta.setText("Registrar venta");
        opRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRegistrarVentaActionPerformed(evt);
            }
        });
        jMenu2.add(opRegistrarVenta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        opListarReporte.setText("Listar reporte");
        opListarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opListarReporteActionPerformed(evt);
            }
        });
        jMenu3.add(opListarReporte);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opRegistrarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRegistrarEquipoActionPerformed
        RegistrarEquipo verequipo = new RegistrarEquipo();
        escritorio.add(verequipo);
        verequipo.show();
    }//GEN-LAST:event_opRegistrarEquipoActionPerformed

    private void opRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRegistrarClienteActionPerformed
        RegistrarCliente vercliente = new RegistrarCliente();
        escritorio.add(vercliente);
        vercliente.show();
    }//GEN-LAST:event_opRegistrarClienteActionPerformed

    private void opRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRegistrarVentaActionPerformed
        RegistrarVenta verventa = new RegistrarVenta();
        escritorio.add(verventa);
        verventa.show();
    }//GEN-LAST:event_opRegistrarVentaActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void opListarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opListarReporteActionPerformed
        ListarReporte showreporte = new ListarReporte();
        escritorio.add(showreporte);
        showreporte.show();
    }//GEN-LAST:event_opListarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    System.out.println("Prueba 1 2 3");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opListarReporte;
    private javax.swing.JMenuItem opRegistrarCliente;
    private javax.swing.JMenuItem opRegistrarEquipo;
    private javax.swing.JMenuItem opRegistrarVenta;
    // End of variables declaration//GEN-END:variables
}
